### ISSUE TITLE
FreeCAD just did a soft 0.18 release

### ISSUE THREAD

**Issue by luzpaz** [Schamschula/macports#1]
Although the builds are not available yet.. you can test with the 
https://github.com/FreeCAD/FreeCAD/releases/tag/0.18_pre

**Comment by Schamschula** [comment]
Yes, I'm aware of it. Unfortunately, it fails to cleanly build using Qt5 and Python 3.7. I will revisit next week.

**Comment by Schamschula** [comment]
It looks like there is a 0.18.1 release. I will try building w/o Qt5 and Python 3.7, and then work each in.

**Comment by luzpaz** [comment]
any progress ?

**Comment by Schamschula** [comment]
Unfortunately, there are blockers in dependencies.

Last week, 0.18.2 came out, but I haven't had a chance to try to build it.

**Comment by Schamschula** [comment]
0.18.2 still doesn't build with qt5 or python 3.7, but here is an updated Portfile for qt4 and python 2.7:

https://github.com/Schamschula/macports/commit/c59598fc25763567236f8f257acf394a2dca1a5e

Note: The only new patch file is `patch-src-Main-MainPy.cpp.diff` (there are other variants of `patch-CMakeLists.txt.diff` from attempted builds using py37 and qt5).

The bottom line is that the python 3.7 binding for qt5 can't be detected, as cmake is looking for non-existent files in pyside2.

**Comment by luzpaz** [comment]
@Schamschula please post on the FreeCAD forums. We really need this port to move away from py2/qt4  
What are the issues you are seeing that are blocking py3/qt5 compilations ?

**Comment by Schamschula** [comment]
I'd rather try to do these changes in two steps:

1) python 3.7
2) qt5

The order doesn't matter, but changing both at the same time is asking for trouble.

py-pivy makes the jump to qt5 at version 0.6.3. Apparently, 0.6.4 also supports qt4. I'll give a py37 version a try.

From by previous build attempts. the freecad patchset for qt5 seems to be incomplete.

**Comment by luzpaz** [comment]
Please post the [FreeCAD Packaging subforum](https://forum.freecadweb.org/viewforum.php?f=42) as well, if you need help or want to update the community.

**Comment by Schamschula** [comment]
My first attempt to patch py-pivy has stalled on the SoQt module.

The funky way of using cmake from within python is a problem. I can't figure out how to tell cmake where to look for SoQt.
