### ISSUE TITLE
Update netcdf to 4.7.0

### ISSUE THREAD

**Issue by luzpaz** [Schamschula/macports#11]
Existing Macport: https://github.com/macports/macports-ports/tree/master/science/netcdf  
Release announcement: https://www.unidata.ucar.edu/blogs/news/entry/netcdf-4-7-0  
Release: https://github.com/Unidata/netcdf-c/releases/v4.7.0

**Comment by Schamschula** [comment]
See https://github.com/macports/macports-ports/pull/4689

**Comment by luzpaz** [comment]
Done. Thanks you @Schamschula  
https://github.com/macports/macports-ports/commit/f2e6b96801773f6b8af7e5358c3f2c6d5dd94bd7
