### ISSUE TITLE
Update imagemagick to 7.0.8-50

### ISSUE THREAD

**Issue by luzpaz** [Schamschula/macports#13]
https://github.com/ImageMagick/ImageMagick/releases
macports is still using Imagemagick 6 (https://github.com/macports/macports-ports/blob/master/graphics/ImageMagick/Portfile#L12) as you know. What's the reason for that?

**Comment by Schamschula** [comment]
The maintainer of the ImageMagick port is Ryan Schmidt. Please add a ticket at https://trac.macports.org

**Comment by luzpaz** [comment]
https://github.com/macports/macports-ports/pull/5016
