### ISSUE TITLE
oda-file-converter needs to be added to macports

### ISSUE THREAD

**Issue by luzpaz** [Schamschula/macports#5]
`oda-file-converter` replaces the `teighafileconverter`  
This is a dependency in FreeCAD.  
Here is the Arch Linux package for it: https://aur.archlinux.org/packages/oda-file-converter

**Comment by Schamschula** [comment]
Hmm. No source code, only installer packages.

**Comment by luzpaz** [comment]
Yea, they made it proprietary.   
It used to be called `teighafileconverter`

**Comment by Schamschula** [comment]
That's a non-starter for MacPorts.

**Comment by luzpaz** [comment]
Ok. Thanks anyway.
