### ISSUE TITLE
Add ifcopenshell to macports

### ISSUE THREAD

**Issue by luzpaz** [Schamschula/macports#6]
Used for Arch and BIM workbenches 
http://ifcopenshell.org/  
Example Arch Linux package: https://aur.archlinux.org/packages/ifcopenshell

**Comment by Schamschula** [comment]
My first cut: https://github.com/Schamschula/macports/commit/e7bb42f43c08d8edb29338c08bf311d84b3ebc31

No Collada support.

**Comment by luzpaz** [comment]
Hasn't been merged in to macports yet
